name: 'Get and Alias Vercel Preview URL'
description: 'Get preview URL of a Vercel deployment and alias it automatically'
branding:
  icon: activity
  color: gray-dark
author: 'maceip'
inputs:
  vercel_access_token:
    description: 'https://vercel.com/docs/rest-api#introduction/api-basics/authentication/creating-an-access-token'
    required: true
  vercel_project_id:
    description: 'Get your Project ID from project settings in Vercel management console'
    required: true
  vercel_team_id:
    description: 'https://vercel.com/docs/rest-api#introduction/api-basics/authentication/accessing-resources-owned-by-a-team'
    required: false
  alias_template:
    description: 'template of alias preview url. eg: {random}.e2e-test.mysite.com'
    required: true
    default: 'preview.snowybot.com'
  ref_token:
    description: 'template of alias preview url. eg: {random}.e2e-test.mysite.com'
    required: true
    default: ''
  ref_sha:
    description: 'template of alias preview url. eg: {random}.e2e-test.mysite.com'
    required: true
    default: ''

  scope:
    description: 'https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret'
    required: false
    default: 'appbase-ai'
  github_deployment_generated:
    description: 'url created automatically by vercel/gh'
    required: true
    default: ''

outputs:
  preview_url_alias:
    description: 'Alias of Vercel Preview URL'
  preview_url_origin:
    description: 'Original Vercel Preview URL'
  status:
    description: 'Status of the Vercel deployment'
runs:
  using: 'node16'
  main: 'dist/index.js'
