name: Assign Vercel Preview
on:
  deployment_status:

jobs:
get_ref_name:
  runs-on: self-hosted
  outputs:
    ref_name: ${{ steps.get_ref_name.outputs.ref_name }}
  steps:
    - name: Get ref_name
      id: get_ref_name
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "ref_name=${{ github.base_ref }}"
          echo "ref_name=${{ github.base_ref }}" >> $GITHUB_OUTPUT || exit 1
        else
          echo "ref_name=${{ github.ref_name }}"
          echo "ref_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT || exit 1
        fi  
        
domain-linker-windows-runner:
  needs: get_ref_name
  if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
  runs-on: self-hosted
  environment:
    name: ${{ needs.get_ref_name.outputs.ref_name }}
  steps:
  - name: call-vercel
    uses: appbase-ai/vercel-action@v1.26
    with:
      vercel_access_token: ${{ secrets.VERCEL_TOKEN }}
      vercel_team_id: ${{ secrets.VERCEL_TEAM_ID }}
      vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
      alias_template: 'snowybot.com'
      github_deployment_generated: ${{ github.event.deployment_status.target_url }}
      scope: 'appbase-ai'
      ref_token: ${{ secrets.REF_TOKEN}}
      ref_sha: ${{ needs.get_ref_name.outputs.ref_name }}
